import userRouter from "./user.routes.js";
import reviewRouter from "./review.routes.js";
import bookingRouter from "./booking.routes.js";
import propertyRouter from "./property.routes.js";
import destinationRouter from "./destination.routes.js";
import paymentRouter from "./payment.routes.js";
import hotelRouter from "./hotel.routes.js";
import authRouter from "./auth.routes.js";
import express from "express";
const router = express.Router();
router.use("/user", userRouter);
router.use("/auth", authRouter);
router.use("/review", reviewRouter);
router.use("/hotel", hotelRouter);
router.use("/destination", destinationRouter);
router.use("/property", propertyRouter);
router.use("/payment", paymentRouter);
router.use("/booking", bookingRouter);
export default router;
